### ISSUE TITLE
clean CMIP6 fails on CNRM-ESM2-1 tasmax and tasmin and CNRM-CM6-1 tasmin due to chunking issue 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#208]
```
az://clean-cmip6/IPSL-CM6A-LR/historical/tasmax.zarr
az://scratch/clean-cmip6-ncsr5/clean-cmip6-ncsr5-1694746566/out.zarr
ds1:
<xarray.Dataset>
Dimensions:      (lat: 143, lon: 144, time: 23725, axis_nbounds: 2)
Coordinates:
  * lat          (lat) float32 -90.0 -88.73 -87.46 -86.2 ... 87.46 88.73 90.0
  * lon          (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
  * time         (time) object 1950-01-01 12:00:00 ... 2014-12-31 12:00:00
    time_bounds  (time, axis_nbounds) datetime64[ns] dask.array<chunksize=(23725, 1), meta=np.ndarray>
Dimensions without coordinates: axis_nbounds
Data variables:
    tasmax       (time, lat, lon) float32 dask.array<chunksize=(365, 143, 144), meta=np.ndarray>
Attributes: (12/56)
    CMIP6_CV_version:        cv=6.2.3.5-2-g63b123e
    Conventions:             CF-1.7 CMIP-6.2
    EXPID:                   historical
    NCO:                     "4.6.0"
    activity_id:             CMIP
    branch_method:           standard
    ...                      ...
    table_id:                day
    title:                   IPSL-CM6A-LR model output prepared for CMIP6 / C...
    tracking_id:             hdl:21.14100/ba5dec0a-dc99-4c65-aa68-60151acc61c4
    variable_id:             tasmax
    variant_label:           r1i1p1f1
    version_id:              v20190614
ds2:
<xarray.Dataset>
Dimensions:      (lat: 143, lon: 144, time: 31390, axis_nbounds: 2)
Coordinates:
  * lat          (lat) float32 -90.0 -88.73 -87.46 -86.2 ... 87.46 88.73 90.0
  * lon          (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
  * time         (time) object 2015-01-01 12:00:00 ... 2100-12-31 12:00:00
    time_bounds  (time, axis_nbounds) datetime64[ns] dask.array<chunksize=(15706, 2), meta=np.ndarray>
Dimensions without coordinates: axis_nbounds
Data variables:
    tasmax       (time, lat, lon) float32 dask.array<chunksize=(730, 143, 144), meta=np.ndarray>
Attributes: (12/56)
    CMIP6_CV_version:        cv=6.2.3.5-2-g63b123e
    Conventions:             CF-1.7 CMIP-6.2
    EXPID:                   ssp370
    activity_id:             ScenarioMIP AerChemMIP
    branch_method:           standard
    branch_time_in_child:    0.0
    ...                      ...
    title:                   IPSL-CM6A-LR model output prepared for CMIP6 / S...
    tracking_id:             hdl:21.14100/5a96d6cb-bad6-423c-8843-1833cdfb14ff
    variable_id:             tasmax
    variant_info:            Each member starts from the corresponding member...
    variant_label:           r1i1p1f1
    version_id:              v20190614
Traceback (most recent call last):
  File "/argo/staging/script", line 19, in <module>
    ds = ds.chunk({"time": 365, "lat": -1, "lon": -1, "bnds": 2})
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2157, in chunk
    raise ValueError(
ValueError: some chunks keys are not dimensions on this object: {'bnds'}
```

**Comment by dgergel** [comment]
CNRM-ESM2-1 fails for the same reason: 

```
az://clean-cmip6/CNRM-ESM2-1/historical/tasmax.zarr
az://scratch/clean-cmip6-nbqn4/clean-cmip6-nbqn4-4293413317/out.zarr
ds1:
<xarray.Dataset>
Dimensions:      (lat: 128, lon: 256, time: 23725, axis_nbounds: 2)
Coordinates:
  * lat          (lat) float64 -88.93 -87.54 -86.14 -84.74 ... 86.14 87.54 88.93
  * lon          (lon) float64 0.0 1.406 2.812 4.219 ... 354.4 355.8 357.2 358.6
  * time         (time) object 1950-01-01 12:00:00 ... 2014-12-31 12:00:00
    time_bounds  (time, axis_nbounds) datetime64[ns] dask.array<chunksize=(23725, 1), meta=np.ndarray>
Dimensions without coordinates: axis_nbounds
Data variables:
    tasmax       (time, lat, lon) float32 dask.array<chunksize=(365, 128, 256), meta=np.ndarray>
Attributes: (12/57)
    CMIP6_CV_version:        cv=6.2.3.0-7-g2019642
    Conventions:             CF-1.7 CMIP-6.2
    EXPID:                   CNRM-ESM2-1_historical_r1i1p1f2
    activity_id:             CMIP
    arpege_minor_version:    6.3.2
    branch_method:           standard
    ...                      ...
    title:                   CNRM-ESM2-1 model output prepared for CMIP6 / CM...
    tracking_id:             hdl:21.14100/777cd1a8-2c8a-4a84-8dd7-29a1df8614d0
    variable_id:             tasmax
    variant_label:           r1i1p1f2
    version_id:              v20181206
    xios_commit:             1442-shuffle
ds2:
<xarray.Dataset>
Dimensions:      (lat: 128, lon: 256, time: 31390, axis_nbounds: 2)
Coordinates:
  * lat          (lat) float64 -88.93 -87.54 -86.14 -84.74 ... 86.14 87.54 88.93
  * lon          (lon) float64 0.0 1.406 2.812 4.219 ... 354.4 355.8 357.2 358.6
  * time         (time) object 2015-01-01 12:00:00 ... 2100-12-31 12:00:00
    time_bounds  (time, axis_nbounds) datetime64[ns] dask.array<chunksize=(15706, 2), meta=np.ndarray>
Dimensions without coordinates: axis_nbounds
Data variables:
    tasmax       (time, lat, lon) float32 dask.array<chunksize=(730, 128, 256), meta=np.ndarray>
Attributes: (12/57)
    CMIP6_CV_version:        cv=6.2.3.0-7-g2019642
    Conventions:             CF-1.7 CMIP-6.2
    EXPID:                   CNRM-ESM2-1_ssp370_r1i1p1f2_AOESM_ssp370_r1_rerun
    activity_id:             ScenarioMIP AerChemMIP
    arpege_minor_version:    6.3.2
    branch_method:           standard
    ...                      ...
    title:                   CNRM-ESM2-1 model output prepared for CMIP6 / Sc...
    tracking_id:             hdl:21.14100/54524962-9a6c-440b-b4d2-e80271df1766
    variable_id:             tasmax
    variant_label:           r1i1p1f2
    version_id:              v20191021
    xios_commit:             1442-shuffle
Traceback (most recent call last):
  File "/argo/staging/script", line 19, in <module>
    ds = ds.chunk({"time": 365, "lat": -1, "lon": -1, "bnds": 2})
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2157, in chunk
    raise ValueError(
ValueError: some chunks keys are not dimensions on this object: {'bnds'}
```
