### ISSUE TITLE
download CMIP6 fails on ACCESS-CM2 ssp126 because of datetime issue with writing zarr store 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#210]
```
Searching catalog
Found one catalog entry ['ScenarioMIP.MRI.MRI-ESM2-0.ssp126.day.gn']
{'ScenarioMIP.MRI.MRI-ESM2-0.ssp126.day.gn': <xarray.Dataset>
Dimensions:    (lat: 160, bnds: 2, lon: 320, member_id: 1, time: 104459)
Coordinates:
    height     float64 ...
  * lat        (lat) float64 -89.14 -88.03 -86.91 -85.79 ... 86.91 88.03 89.14
    lat_bnds   (lat, bnds) float64 dask.array<chunksize=(160, 2), meta=np.ndarray>
  * lon        (lon) float64 0.0 1.125 2.25 3.375 ... 355.5 356.6 357.8 358.9
    lon_bnds   (lon, bnds) float64 dask.array<chunksize=(320, 2), meta=np.ndarray>
  * time       (time) object 2015-01-01 12:00:00 ... 2300-12-31 12:00:00
    time_bnds  (time, bnds) object dask.array<chunksize=(52230, 1), meta=np.ndarray>
  * member_id  (member_id) <U8 'r1i1p1f1'
Dimensions without coordinates: bnds
Data variables:
    tasmax     (member_id, time, lat, lon) float32 dask.array<chunksize=(1, 853, 160, 320), meta=np.ndarray>
Attributes: (12/49)
    Conventions:             CF-1.7 CMIP-6.2
    activity_id:             ScenarioMIP
    branch_method:           standard
    branch_time_in_child:    60265.0
    branch_time_in_parent:   60265.0
    cmor_version:            3.4.0
    ...                      ...
    variable_id:             tasmax
    variant_label:           r1i1p1f1
    netcdf_tracking_ids:     hdl:21.14100/be6aceb0-5774-4fd4-ae4e-2cde85d2b67...
    version_id:              v20191108
    intake_esm_varname:      ['tasmax']
    intake_esm_dataset_key:  ScenarioMIP.MRI.MRI-ESM2-0.ssp126.day.gn}
/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py:527: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py:527: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
/opt/conda/lib/python3.9/site-packages/numpy/core/_asarray.py:102: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  return array(a, dtype, copy=False, order=order)
/opt/conda/lib/python3.9/site-packages/numpy/core/_asarray.py:102: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "/argo/staging/script", line 27, in <module>
    dodola.repository.write(outpath, d[k[0]])
  File "/opt/dodola/dodola/repository.py", line 42, in write
    x.to_zarr(url_or_path, mode="w", compute=True)
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2031, in to_zarr
    return to_zarr(
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1415, in to_zarr
    writes = writer.sync(compute=compute)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/common.py", line 167, in sync
    delayed_store = da.store(
  File "/opt/conda/lib/python3.9/site-packages/dask/array/core.py", line 1028, in store
    result.compute(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 514, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 325, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/conda/lib/python3.9/site-packages/dask/optimization.py", line 966, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/conda/lib/python3.9/site-packages/dask/utils.py", line 34, in apply
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/array/chunk.py", line 269, in astype
    return x.astype(astype_dtype, **kwargs)
TypeError: float() argument must be a string or a number, not 'cftime._cftime.DatetimeProlepticGregorian'
```

**Comment by dgergel** [comment]
@brews looks to me like there is an issue with the data itself? Have you seen this error before?

**Comment by dgergel** [comment]
ACCESS-CM2 has the same issue for ssp126: 

```
Searching catalog
Found one catalog entry ['ScenarioMIP.CSIRO-ARCCSS.ACCESS-CM2.ssp126.day.gn']
{'ScenarioMIP.CSIRO-ARCCSS.ACCESS-CM2.ssp126.day.gn': <xarray.Dataset>
Dimensions:    (lat: 144, bnds: 2, lon: 192, member_id: 1, time: 104459)
Coordinates:
    height     float64 ...
  * lat        (lat) float64 -89.38 -88.12 -86.88 -85.62 ... 86.88 88.12 89.38
    lat_bnds   (lat, bnds) float64 dask.array<chunksize=(144, 2), meta=np.ndarray>
  * lon        (lon) float64 0.9375 2.812 4.688 6.562 ... 355.3 357.2 359.1
    lon_bnds   (lon, bnds) float64 dask.array<chunksize=(192, 2), meta=np.ndarray>
  * time       (time) object 2015-01-01 12:00:00 ... 2300-12-31 12:00:00
    time_bnds  (time, bnds) object dask.array<chunksize=(52230, 1), meta=np.ndarray>
  * member_id  (member_id) <U8 'r1i1p1f1'
Dimensions without coordinates: bnds
Data variables:
    tasmax     (member_id, time, lat, lon) float32 dask.array<chunksize=(1, 658, 144, 192), meta=np.ndarray>
Attributes: (12/52)
    Conventions:             CF-1.7 CMIP-6.2
    activity_id:             ScenarioMIP
    branch_method:           standard
    branch_time_in_child:    60265.0
    branch_time_in_parent:   60265.0
    cmor_version:            3.4.0
    ...                      ...
    variable_id:             tasmax
    variant_label:           r1i1p1f1
    version:                 v20191108
    version_id:              v20210317
    intake_esm_varname:      ['tasmax']
    intake_esm_dataset_key:  ScenarioMIP.CSIRO-ARCCSS.ACCESS-CM2.ssp126.day.gn}
/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py:527: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
/opt/conda/lib/python3.9/site-packages/xarray/coding/times.py:527: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
/opt/conda/lib/python3.9/site-packages/numpy/core/_asarray.py:102: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  return array(a, dtype, copy=False, order=order)
/opt/conda/lib/python3.9/site-packages/numpy/core/_asarray.py:102: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "/argo/staging/script", line 27, in <module>
    dodola.repository.write(outpath, d[k[0]])
  File "/opt/dodola/dodola/repository.py", line 42, in write
    x.to_zarr(url_or_path, mode="w", compute=True)
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2031, in to_zarr
    return to_zarr(
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1415, in to_zarr
    writes = writer.sync(compute=compute)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/common.py", line 167, in sync
    delayed_store = da.store(
  File "/opt/conda/lib/python3.9/site-packages/dask/array/core.py", line 1028, in store
    result.compute(**kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 514, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 325, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/conda/lib/python3.9/site-packages/dask/optimization.py", line 966, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/conda/lib/python3.9/site-packages/dask/utils.py", line 34, in apply
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/array/chunk.py", line 269, in astype
    return x.astype(astype_dtype, **kwargs)
TypeError: float() argument must be a string or a number, not 'cftime._cftime.DatetimeProlepticGregorian'
```

**Comment by brews** [comment]
I got MRI-ESM2-0-tasmax.yaml to successfully download, but it fails cmip6 cleaning as described in #356.

I'm going to update the title to reflect this.

**Comment by brews** [comment]
I'm closing this because ACCESS-CM2 gets through the downloading step in https://argo.cildc6.org/workflows/default/e2e-tasmax-jobs-tv4q6

The underlying issue here reemerged in #348 in the cleaning step. We'll deal with that there.
