### ISSUE TITLE
QDM, AIQPD workflow steps fail without units metadata in dodola >= v0.7.0

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#292]
Workflows (e.g. https://argo.cildc6.org/workflows/default/biascorrectdownscale-44qn9) have failed with dodola:0.7.0 because the cleaned ERA-5 renanlysis data is missing "units" attrs/metadata in its variables.

Example of log with the error:
```
reading gs://scratch-170cd6ec/biascorrectdownscale-44qn9/biascorrectdownscale-44qn9-1036909359/rechunked.zarr
reading gs://scratch-170cd6ec/biascorrectdownscale-44qn9/biascorrectdownscale-44qn9-1093943038/rechunked.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 25, in <module>
    qdm = train_quantiledeltamapping(
  File "/opt/dodola/dodola/core.py", line 46, in train_quantiledeltamapping
    qdm = sdba.adjustment.QuantileDeltaMapping.train(
  File "/opt/conda/lib/python3.9/site-packages/xclim/sdba/adjustment.py", line 153, in train
    (ref, hist), train_units = cls._harmonize_units(ref, hist)
  File "/opt/conda/lib/python3.9/site-packages/xclim/sdba/adjustment.py", line 110, in _harmonize_units
    target = inputs[0].units
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/common.py", line 239, in __getattr__
    raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'
```

Looking at the input files, the CMIP6 data appears to have the requires attrs:

```
In [13]: d['tasmax']
Out[13]:
<xarray.DataArray 'tasmax' (time: 7315, lat: 180, lon: 360)>
[474012000 values with dtype=float32]
Coordinates:
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * lon      (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
  * time     (time) object 1994-12-17 12:00:00 ... 2014-12-31 12:00:00
Attributes:
    cell_measures:  area: areacella
    cell_methods:   area: mean time: maximum
    coordinates:    height
    interp_method:  conserve_order2
    long_name:      Daily Maximum Near-Surface Air Temperature
    original_name:  tasmax
    standard_name:  air_temperature
    units:          K
```

ERA-5 does not:
```
In [9]: d['tasmax']
Out[9]:
<xarray.DataArray 'tasmax' (time: 8030, lat: 180, lon: 360)>
[520344000 values with dtype=float32]
Coordinates:
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * lon      (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
  * time     (time) object 1994-01-01 00:00:00 ... 2015-12-31 00:00:00
Attributes:
    coordinates:  dayofyear
```

**Comment by brews** [comment]
Solution is to add this "units" attrs to each ERA-5 variable.

The quick and dirty way to do this is making this an addition to downscaleCMIP6/workflows/templates/clean-era5.yaml, if not the source data.
