### ISSUE TITLE
KACE-1-0-G-tasmax.yaml fails clean-cmip6 "standardize" steps due to 360 calendar.

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#354]
An end-to-end run of KACE-1-0-G-tasmax.yaml (https://argo.cildc6.org/workflows/default/e2e-kace-1-0-g-tasmax-x8kn9) failed the cleaning workflow hard due to its 360 day calendar.

Block progress on run #188.

This will need to be rerun once #181 is resolved.

The full log for one of the failures is here:

```
-1-0-G/ssp126/r1i1p1f1/day/tasmax/gr/v20200317.zarr', 'gs://scratch-170cd6ec/cdb70c56-c74d-4650-b956-71c8b9e50138/e2e-
kace-1-0-g-tasmax-x8kn9-1314524591/standardized.zarr', True), kwargs={})
INFO:dodola.repository:Read gs://raw-305d04da/cmip6/ScenarioMIP/NIMS-KMA/KACE-1-0-G/ssp126/r1i1p1f1/day/tasmax/gr/v202
00317.zarr
Traceback (most recent call last):
  File "/opt/conda/bin/dodola", line 33, in <module>
    sys.exit(load_entry_point('dodola', 'console_scripts', 'dodola')())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/dodola/dodola/cli.py", line 436, in cleancmip6
    services.clean_cmip6(x, out, drop_leapdays)
  File "/opt/dodola/dodola/services.py", line 31, in service_logger
    func(*args, **kwargs)
  File "/opt/dodola/dodola/services.py", line 640, in clean_cmip6
    cleaned_ds = standardize_gcm(ds, leapday_removal)
  File "/opt/dodola/dodola/core.py", line 517, in standardize_gcm
    ds_noleap = xclim_remove_leapdays(ds_cleaned)
  File "/opt/dodola/dodola/core.py", line 538, in xclim_remove_leapdays
    ds_noleap = convert_calendar(ds, target="noleap")
  File "/opt/conda/lib/python3.9/site-packages/xclim/core/calendar.py", line 211, in convert_calendar
    raise ValueError(
ValueError: Argument `align_on` must be specified with either 'date', 'year' or 'random' when converting to or from a
'360_day' calendar.
```

**Comment by dgergel** [comment]
@emileten now that we have 360-cal support can we retry this?

**Comment by brews** [comment]
This is a duplicate of #439 — which has a more thorough description of the issue in a more recent run. It looks like it might be an issue beyond just adding 360 calendar support. I'm going to close this.
