### ISSUE TITLE
MIROC6-tasmax.yaml fails clean-cmip6 validation with bad tasmax values for ssp126, ssp245, ssp370, ssp585 

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#358]
MIROC6-tasmax.yaml fails its end-to-end run in the clean cmip6 workflow with bad validation for the tasmax variable.

This is from run https://argo.cildc6.org/workflows/default/e2e-miroc6-tasmax-rnd98

Blocking progress on run #191 

Log from ssp585:
```
Validating gs://clean-b1dbca25/cmip6/ScenarioMIP/MIROC/MIROC6/ssp585/r1i1p1f1/day/tasmax/gn/v20191016.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 44, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 29, in clear_memory_intensive_tests
    _test_temp_range(d, v)
  File "/opt/dodola/dodola/core.py", line 684, in _test_temp_range
    assert (ds[var].min() > 150) and (
AssertionError: tasmax values are invalid
```

Similar errors in logs for other ssps zarrs:
```
gs://clean-b1dbca25/cmip6/ScenarioMIP/MIROC/MIROC6/ssp126/r1i1p1f1/day/tasmax/gn/v20191016.zarr
gs://clean-b1dbca25/cmip6/ScenarioMIP/MIROC/MIROC6/ssp245/r1i1p1f1/day/tasmax/gn/v20191016.zarr
gs://clean-b1dbca25/cmip6/ScenarioMIP/MIROC/MIROC6/ssp370/r1i1p1f1/day/tasmax/gn/v20191016.zarr
```

**Comment by brews** [comment]
Closed with PR #365
