### ISSUE TITLE
CanESM5-tasmax.yaml fails to apply QDM biascorrection to historical with "KeyError: '2026'"

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#368]
From workflow: https://argo.cildc6.org/archived-workflows/default/34ea8242-a749-41da-aa5e-1a8ecbf34f65

All latitude bands failed to apply QDM with a similar error. Example log output:

```
INFO:dodola.services:Starting dodola service apply_qdm with args=(), kwargs={'simulation': 'gs://scratch-170cd6ec/34ea
8242-a749-41da-aa5e-1a8ecbf34f65/e2e-canesm5-tasmax-76djb-1403710222/preprocessed.zarr', 'qdm': 'gs://scratch-170cd6ec
/34ea8242-a749-41da-aa5e-1a8ecbf34f65/e2e-canesm5-tasmax-76djb-1327698454/qdm_model.zarr', 'years': range(1950, 2100),
 'variable': 'tasmax', 'out': 'gs://scratch-170cd6ec/34ea8242-a749-41da-aa5e-1a8ecbf34f65/e2e-canesm5-tasmax-76djb-339
7810253/qdm_adjusted.zarr', 'sel_slice': None, 'isel_slice': {'lat': slice(170, 180, None)}, 'out_zarr_region': {'lat'
: slice(170, 180, None)}, 'root_attrs_json_file': '/tmp/global_attrs.json', 'new_attrs': None})
INFO:dodola.repository:Read gs://scratch-170cd6ec/34ea8242-a749-41da-aa5e-1a8ecbf34f65/e2e-canesm5-tasmax-76djb-140371
0222/preprocessed.zarr
INFO:dodola.repository:Read gs://scratch-170cd6ec/34ea8242-a749-41da-aa5e-1a8ecbf34f65/e2e-canesm5-tasmax-76djb-132769
8454/qdm_model.zarr
INFO:dodola.services:Using root attrs from /tmp/global_attrs.json
INFO:dodola.repository:Read attrs from /tmp/global_attrs.json
INFO:dodola.services:Slicing by isel_slice={'lat': slice(170, 180, None)}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/cftimeindex.py", line 430, in _get_string_slice
    loc = self._partial_date_slice(resolution, parsed)
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/cftimeindex.py", line 415, in _partial_date_slice
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/dodola", line 33, in <module>
    sys.exit(load_entry_point('dodola', 'console_scripts', 'dodola')())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/dodola/dodola/cli.py", line 231, in apply_qdm
    services.apply_qdm(
  File "/opt/dodola/dodola/services.py", line 32, in service_logger
    func(*args, **kwargs)
  File "/opt/dodola/dodola/services.py", line 317, in apply_qdm
    adjusted_ds = adjust_quantiledeltamapping(
  File "/opt/dodola/dodola/core.py", line 101, in adjust_quantiledeltamapping
    adj = adjust_quantiledeltamapping_year(
  File "/opt/dodola/dodola/core.py", line 175, in adjust_quantiledeltamapping_year
    out = qdm.adjust(simulation, interp="nearest").sel(time=str(year))
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2474, in sel
    pos_indexers, new_indexes = remap_label_indexers(
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/coordinates.py", line 421, in remap_label_indexers
    pos_indexers, new_indexes = indexing.remap_label_indexers(
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/indexing.py", line 117, in remap_label_indexers
    idxr, new_idx = index.query(labels, method=method, tolerance=tolerance)
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/indexes.py", line 224, in query
    indexer = index.get_loc(
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/cftimeindex.py", line 464, in get_loc
    return self._get_string_slice(key)
  File "/opt/conda/lib/python3.9/site-packages/xarray/coding/cftimeindex.py", line 432, in _get_string_slice
    raise KeyError(key)
KeyError: '2026'
```
Other ssps succeeded and were validated apparently without issue. Something is special with this historical data.

Blocking progress on #189

**Comment by brews** [comment]
Nudging @dgergel. This one is a little different.
