### ISSUE TITLE
GFDL-CM4-tasmax.yaml and GFDL-ESM4-tasmax.yaml fail cleaning ssp, historical concatenation

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#435]
GFDL-CM4-tasmax.yaml and GFDL-ESM4-tasmax.yaml fail cleaning ssp, historical concatenation. This happens for all ssps and historical.

This is from workflows:
- https://argo.cildc6.org/archived-workflows/default/2bfa8ccd-6625-4954-b6e7-4a7c04aa773f
- https://argo.cildc6.org/archived-workflows/default/17189222-c63d-400b-a5f9-4b2831568ddc

Example of logged error from one of the historical runs:
```
gs://scratch-170cd6ec/2bfa8ccd-6625-4954-b6e7-4a7c04aa773f/e2e-gfdl-esm4-tasmax-znftl-1503470942/standardized.zarr
gs://scratch-170cd6ec/2bfa8ccd-6625-4954-b6e7-4a7c04aa773f/e2e-gfdl-esm4-tasmax-znftl-5603963/timesliced.zarr
ds1:
<xarray.Dataset>
Dimensions:  (lat: 180, lon: 288, time: 23725)
Coordinates:
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * lon      (lon) float64 0.625 1.875 3.125 4.375 ... 355.6 356.9 358.1 359.4
  * time     (time) object 1950-01-01 12:00:00 ... 2014-12-31 12:00:00
Data variables:
    tasmax   (time, lat, lon) float32 dask.array<chunksize=(730, 180, 288), meta=np.ndarray>
Attributes: (12/51)
    Conventions:             CF-1.7 CMIP-6.0 UGRID-1.0
    activity_id:             CMIP
    branch_method:           standard
    branch_time_in_child:    0.0
    branch_time_in_parent:   36500.0
    comment:                 <null ref>
    ...                      ...
    title:                   NOAA GFDL GFDL-ESM4 model output prepared for CM...
    tracking_id:             hdl:21.14100/58ac0879-1713-40d5-9a5f-d2a262afdef...
    variable_id:             tasmax
    variant_info:            N/A
    variant_label:           r1i1p1f1
    version_id:              v20190726
ds2:
<xarray.Dataset>
Dimensions:  (lat: 180, lon: 288, time: 4015)
Coordinates:
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * lon      (lon) float64 0.625 1.875 3.125 4.375 ... 355.6 356.9 358.1 359.4
  * time     (time) object 2015-01-01 12:00:00 ... 2025-12-31 12:00:00
Data variables:
    tasmax   (time, lat, lon) float32 dask.array<chunksize=(365, 180, 288), meta=np.ndarray>
Attributes: (12/51)
    Conventions:             CF-1.7 CMIP-6.0 UGRID-1.0
    activity_id:             ScenarioMIP
    branch_method:           standard
    branch_time_in_child:    60225.0
    branch_time_in_parent:   60225.0
    comment:                 <null ref>
    ...                      ...
    title:                   NOAA GFDL GFDL-ESM4 model output prepared for CM...
    tracking_id:             hdl:21.14100/968a1f24-b80f-41bc-99e4-6e22d2fccc4...
    variable_id:             tasmax
    variant_info:            N/A
    variant_label:           r1i1p1f1
    version_id:              v20180701
Traceback (most recent call last):
  File "/argo/staging/script", line 23, in <module>
    ds = ds.chunk({"time": 365, "lat": -1, "lon": -1, "bnds": 2})
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2157, in chunk
    raise ValueError(
ValueError: some chunks keys are not dimensions on this object: {'bnds'}
```

Errors appear the same across the failed runs.

Blocking progress on #317 and #198

**Comment by brews** [comment]
Taking a guess at this, it's looking for `bnds` which does not exist in the "raw" GFDL data.

For example, the raw data for MIROC6 has
```
...
Dimensions:   (lat: 128, bnds: 2, lon: 256, time: 23725)
Coordinates:
  * lat       (lat) float64 -88.93 -87.54 -86.14 -84.74 ... 86.14 87.54 88.93
    lat_bnds  (lat, bnds) float64 dask.array<chunksize=(128, 2), meta=np.ndarray>
  * lon       (lon) float64 0.0 1.406 2.812 4.219 ... 354.4 355.8 357.2 358.6
    lon_bnds  (lon, bnds) float64 dask.array<chunksize=(256, 2), meta=np.ndarray>
  * time      (time) object 1950-01-01 12:00:00 ... 2014-12-31 12:00:00
Dimensions without coordinates: bnds
...
```

**Comment by dgergel** [comment]
Yeah that's what it looks like to me as well. I don't think this is a pre-processing issue as I didn't alter the raw data other than the tasmax/tasmin swap, but I'll double check that they didn't somehow get dropped in that step. My guess is that they just aren't in the raw files. 

Do we need to add `bnds` for conservative area regridding for precip? I know we have talked about this before and I can't recall what the situation is currently, there may be a newer feature in xesmf that infers the bounds if they aren't present. If not, I think that the cmip6_preprocessing package can infer/add them. 

Otherwise we can just update that cmip6 cleaning check to only look for and chunk by `bnds` if they are present in the raw data.

**Comment by brews** [comment]
This is from the log of the last GFDL-ESM4 run for that same step that failed:
```
<xarray.Dataset>
Dimensions:   (bnds: 2, lat: 180, lon: 288, time: 4015)
Coordinates:
  * bnds      (bnds) float64 1.0 2.0
  * lat       (lat) float64 -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
    lat_bnds  (lat, bnds) float64 dask.array<chunksize=(180, 2), meta=np.ndarray>
  * lon       (lon) float64 0.625 1.875 3.125 4.375 ... 355.6 356.9 358.1 359.4
    lon_bnds  (lon, bnds) float64 dask.array<chunksize=(288, 2), meta=np.ndarray>
  * time      (time) object 2015-01-01 12:00:00 ... 2025-12-31 12:00:00
Data variables:
    tasmax    (time, lat, lon) float32 dask.array<chunksize=(365, 180, 288), meta=np.ndarray>
Attributes: (12/51)
    Conventions:             CF-1.7 CMIP-6.0 UGRID-1.0
    activity_id:             ScenarioMIP
    branch_method:           standard
    branch_time_in_child:    60225.0
    branch_time_in_parent:   60225.0
    comment:                 <null ref>
    ...                      ...
    title:                   NOAA GFDL GFDL-ESM4 model output prepared for CM...
    tracking_id:             hdl:21.14100/968a1f24-b80f-41bc-99e4-6e22d2fccc4...
    variable_id:             tasmax
    variant_info:            N/A
    variant_label:           r1i1p1f1
    version_id:              v20180701
gs://clean-b1dbca25/cmip6/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/day/tasmax/gr1/v20190726.zarr
```

Looks like `bnds` is in the (true) raw data, and we'd want to try to preserve it?

**Comment by dgergel** [comment]
Hmm yeah. Looks like the tasmax/tasmin swapping dropped the `bnds` then. Definitely we do want to preserve that. I don't exactly understand how those got dropped but I'll add them back in and recreate the zarr stores. Sorry about that!

**Comment by dgergel** [comment]
Actually I do not see `bnds` _in_ the (true) raw data now, which is weird. I'll add it in. 

```
tasmax = _get_cmip6_dataset('GFDL-ESM4', 'tasmax', 0, period='historical')
tasmax
```

```
{'CMIP.NOAA-GFDL.GFDL-ESM4.historical.day.gr1': <xarray.Dataset>
 Dimensions:    (member_id: 1, time: 60225, lat: 180, lon: 288)
 Coordinates:
     height     float64 ...
   * lat        (lat) float64 -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
   * lon        (lon) float64 0.625 1.875 3.125 4.375 ... 355.6 356.9 358.1 359.4
   * time       (time) object 1850-01-01 12:00:00 ... 2014-12-31 12:00:00
   * member_id  (member_id) <U8 'r1i1p1f1'
 Data variables:
     tasmax     (member_id, time, lat, lon) float32 dask.array<chunksize=(1, 839, 180, 288), meta=np.ndarray>
 Attributes: (12/51)
     Conventions:             CF-1.7 CMIP-6.0 UGRID-1.0
     activity_id:             CMIP
     branch_method:           standard
     branch_time_in_child:    0.0
     branch_time_in_parent:   36500.0
     comment:                 <null ref>
     ...                      ...
     variant_label:           r1i1p1f1
     status:                  2019-09-27;created;by nhn2@columbia.edu
     netcdf_tracking_ids:     hdl:21.14100/58ac0879-1713-40d5-9a5f-d2a262afdef...
     version_id:              v20190726
     intake_esm_varname:      ['tasmax']
     intake_esm_dataset_key:  CMIP.NOAA-GFDL.GFDL-ESM4.historical.day.gr1}
```

**Comment by brews** [comment]
Ahh, these are different versions. Looking at the parameter files we have `20190726` vs `20180701`.

The snippet I posted above was from `20180701` while yours is from `20190726`. Something to keep an eye on.

**Comment by dgergel** [comment]
@brews the different version numbers are just because yours was an SSP and mine was from historical/CMIP.

**Comment by dgergel** [comment]
closed via the changes added here: https://github.com/ClimateImpactLab/downscaleCMIP6/pull/434
