### ISSUE TITLE
MRI-ESM2-0 pr validation fails on all ssps, there are nans

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#442]
Workflow: https://argo.cildc6.org/archived-workflows/default/742facba-ffde-4590-b78f-67ad624f46e7?nodeId=clean-mri-esm2-0-pr-tvwl9-805502262&container=main&sidePanel=logs

Logs: 

```
Validating gs://clean-b1dbca25/cmip6/ScenarioMIP/MRI/MRI-ESM2-0/ssp585/r1i1p1f1/day/pr/gn/v20191108.zarr
/opt/dodola/dodola/core.py:652: UserWarning: projection cmip6 file has excess timesteps, has 39055
  warnings.warn(
Traceback (most recent call last):
  File "/argo/staging/script", line 44, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 26, in clear_memory_intensive_tests
    _test_for_nans(d, v)
  File "/opt/dodola/dodola/core.py", line 634, in _test_for_nans
    assert ds[var].isnull().sum() == 0, "there are nans!"
AssertionError: there are nans!
```

**Comment by dgergel** [comment]
@brews I checked the cleaned ssp585 zarr and it looks like the entire ssp is all NaNs, here's a figure of "not-nulls" summed over space: 

![image](https://user-images.githubusercontent.com/5017308/146659813-4cd4deef-ad5d-4d82-81b0-1558365c7915.png)

Given that this is in the cleaned pr data this is a data issue, let's move this model for pr to a later deliverable as we may need to reobtain data from ESGF (or original data is all nans too and we remove it entirely)

**Comment by dgergel** [comment]
closing given that both ensemble members we've tried have either missing data or NaNs
