### ISSUE TITLE
CanESM5-dtr.yaml fails validation in "make DTR" step with invalid DTR values for historical

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#447]
The historical-targeted DTR from CanESM5-dtr.yaml fails its validation check due to values outside the expected range. Only the historical target has this problem, other SSPs pass through the validation check.

Workflow is https://argo.cildc6.org/archived-workflows/default/ef761560-d6eb-4532-bcd7-39dcb3a0d004

Logged error is:
```
Validating gs://clean-b1dbca25/cmip6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/day/dtr/gn/v20190429.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 44, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 31, in clear_memory_intensive_tests
    _test_dtr_range(d, v)
  File "/opt/dodola/dodola/core.py", line 719, in _test_dtr_range
    assert (ds[var].min() > 0) and (
AssertionError: diurnal temperature range values are invalid
```

Blocking progress on #259.

**Comment by dgergel** [comment]
Since this isn't part of our Dec. 31st deliverable, moving this to second deliverable milestone 

cc @brews @emileten

**Comment by dgergel** [comment]
closed due to switch to additive approach for tasmin
