### ISSUE TITLE
EC-Earth3-dtr.yaml historical and ssp245 fail downscaling validation with invalid DTR values

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#449]
The DTR biascorrect+downscale run fails for EC-Earth3 because historical and ssp245 fail downscaling validation. ssp126 and ssp585 pass the same validation steps.

Workflow run: https://argo.cildc6.org/archived-workflows/default/3d360122-2a75-4cb3-9c1c-9f3962a000aa

Logs with error for ssp245:
```
Validating gs://downscaled-288ec5ac/stage/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp245/r1i1p1f1/day
/dtr/gr/v20211215231554.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 44, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 31, in clear_memory_intensive_tests
    _test_dtr_range(d, v)
  File "/opt/dodola/dodola/core.py", line 719, in _test_dtr_range
    assert (ds[var].min() > 0) and (
AssertionError: diurnal temperature range values are invalid
```

Logs with error from historical:
```
Validating gs://downscaled-288ec5ac/stage/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/day/dt
r/gr/v20211215231554.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 44, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 31, in clear_memory_intensive_tests
    _test_dtr_range(d, v)
  File "/opt/dodola/dodola/core.py", line 719, in _test_dtr_range
    assert (ds[var].min() > 0) and (
AssertionError: diurnal temperature range values are invalid
```

Blocking progress on #265.

**Comment by dgergel** [comment]
closed due to switch to additive QDM/QPLAD approach
