### ISSUE TITLE
MIROC6-dtr.yaml ssp126, ssp245, ssp345, ssp585 fail bias-correction validation with invalid DTR range

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#450]
The biascorrect+downscaling run for MIROC6 DTR fails when validating bias-corrected output for ssp126, ssp245, ssp345 and ssp585. The validation error says that the DTR values are outside of the valid range. The historical run passes and appears to produce valid downscaled output.

Workflow run: https://argo.cildc6.org/archived-workflows/default/2ae96eca-69cf-47ff-9edb-0447111395e3

Sample logged error from ssp345:
```
Validating gs://biascorrected-492e989a/stage/ScenarioMIP/MIROC/MIROC6/ssp126/r1i1p1f1/day/dtr/gn/v20211
215235807.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 44, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 31, in clear_memory_intensive_tests
    _test_dtr_range(d, v)
  File "/opt/dodola/dodola/core.py", line 719, in _test_dtr_range
    assert (ds[var].min() > 0) and (
AssertionError: diurnal temperature range values are invalid
```

Blocking progress on #397

**Comment by brews** [comment]
Closed by #459
