### ISSUE TITLE
EC-Earth3-Veg-LR-dtr.yaml historical and ssp245 computed DTR fails DTR validation with invalid DTR range

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#453]
EC-Earth3-Veg-LR DTR fails in the "compute DTR" step because the cleaned DTR output for historical and ssp245 fail validation, apparently with DTR values that fall outside the expected range. ssp126, ssp370, ssp585 pass-through this validation without issue.

Here is a sample of the logged error:
```
Validating gs://clean-b1dbca25/cmip6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/day/
dtr/gr/v20200217.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 44, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 31, in clear_memory_intensive_tests
    _test_dtr_range(d, v)
  File "/opt/dodola/dodola/core.py", line 719, in _test_dtr_range
    assert (ds[var].min() > 0) and (
AssertionError: diurnal temperature range values are invalid
```

From workflow run: https://argo.cildc6.org/archived-workflows/default/12c16eb7-9084-4807-bcec-161b82dc4064

This is blocking progress on #268.

**Comment by dgergel** [comment]
closed due to switch to additive approach for QDM/QPLAD for tasmin
