### ISSUE TITLE
CanESM5 fails e2e DTR run due to failing clean-cmip6 validation 

### ISSUE THREAD

**Issue by dgergel** [ClimateImpactLab/downscaleCMIP6#466]
logs: https://argo.cildc6.org/workflows/default/e2e-canesm5-dtr-55bxm?tab=workflow&nodeId=e2e-canesm5-dtr-55bxm-1236106667

```
Validating gs://clean-b1dbca25/cmip6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/day/dtr/gn/v20190429.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 34, in clear_memory_intensive_tests
    _test_dtr_range(d, v, data_type)
  File "/opt/dodola/dodola/core.py", line 758, in _test_dtr_range
    assert (
AssertionError: diurnal temperature range max is <xarray.DataArray 'dtr' ()>
dask.array<nanmax-aggregate, shape=(), dtype=float32, chunksize=(), chunktype=numpy.ndarray> for non-polar regions
```

**Comment by emileten** [comment]
Seems this is something similar to #468 as well @dgergel.

**Comment by dgergel** [comment]
closed due to switch to additive approach for tasmin
