### ISSUE TITLE
NorESM2-MM e2e DTR run fails biascorrected validation

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#475]
Workflow : https://argo.cildc6.org/archived-workflows/default/854e0457-e566-4e0e-b5d1-1a1d49090e00

Log : 

```
Validating gs://biascorrected-492e989a/stage/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/day/dtr/gn/v20211221191241.zarr
/opt/conda/lib/python3.9/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
/opt/conda/lib/python3.9/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
/opt/conda/lib/python3.9/site-packages/dask/core.py:119: RuntimeWarning: All-NaN slice encountered
  return func(*(_execute_task(a, cache) for a in args))
/opt/conda/lib/python3.9/site-packages/dask/core.py:119: RuntimeWarning: All-NaN slice encountered
  return func(*(_execute_task(a, cache) for a in args))
/opt/conda/lib/python3.9/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
/opt/conda/lib/python3.9/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
/opt/conda/lib/python3.9/site-packages/dask/core.py:119: RuntimeWarning: All-NaN slice encountered
  return func(*(_execute_task(a, cache) for a in args))
/opt/conda/lib/python3.9/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
/opt/conda/lib/python3.9/site-packages/dask/core.py:119: RuntimeWarning: All-NaN slice encountered
  return func(*(_execute_task(a, cache) for a in args))
/opt/conda/lib/python3.9/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
/opt/conda/lib/python3.9/site-packages/dask/core.py:119: RuntimeWarning: All-NaN slice encountered
  return func(*(_execute_task(a, cache) for a in args))
/opt/conda/lib/python3.9/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 34, in clear_memory_intensive_tests
    _test_dtr_range(d, v, data_type)
  File "/opt/dodola/dodola/core.py", line 758, in _test_dtr_range
    assert (
AssertionError: diurnal temperature range max is <xarray.DataArray 'dtr' ()>
dask.array<nanmax-aggregate, shape=(), dtype=float32, chunksize=(), chunktype=numpy.ndarray> for non-polar regions
```

blocks progress on #400

**Comment by emileten** [comment]
88 data points are slightly above the non polar threshold, within 70-75. The range of lats and lons : 

```
array([-78.5,  55.5,  56.5,  57.5,  58.5,  59.5,  60.5,  61.5,  63.5,
        64.5,  65.5,  66.5,  67.5,  68.5,  69.5,  70.5,  72.5,  73.5,
        74.5,  75.5,  76.5])
```

```
array([-176.5, -122.5, -121.5, -120.5, -119.5, -118.5, -117.5, -116.5,
       -109.5, -107.5, -106.5, -105.5,  -94.5,  -93.5,  -92.5,  -91.5,
        -90.5,  -89.5,  -88.5,  -86.5,  -85.5,  -84.5,  -83.5,  -82.5,
        -76.5,  -75.5,  -74.5,  -73.5,  -72.5,  -71.5,  -70.5,  -69.5,
        -68.5,  -67.5,  -66.5,  -65.5,  -64.5,  -63.5,   68.5,   69.5,
         95.5,   96.5,   97.5,   98.5,   99.5,  100.5,  101.5,  102.5,
        103.5,  104.5,  105.5,  106.5,  107.5,  108.5,  109.5,  176.5,
        177.5])
```

**Comment by delgadom** [comment]
I think you posted a fix to this, and the new runs are now failing over the *polar* regions 🙃 :

```python
Validating gs://biascorrected-492e989a/stage/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/day/dtr/gn/v20211230093130.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 34, in clear_memory_intensive_tests
    _test_dtr_range(d, v, data_type)
  File "/opt/dodola/dodola/core.py", line 792, in _test_dtr_range
    assert (
AssertionError: diurnal temperature range max is <xarray.DataArray 'dtr' ()>
dask.array<nanmax-aggregate, shape=(), dtype=float32, chunksize=(), chunktype=numpy.ndarray> for polar northern latitudes
```

I'll take a look

**Comment by dgergel** [comment]
closed due to switch to additive approach for tasmin
