### ISSUE TITLE
GFDL-ESM4 precipitation e2e workflow fails at pre-QPLAD biascorrected output regrid

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#528]
workflow run : https://argo.cildc6.org/archived-workflows/default/97544aa8-da09-4d68-a0e7-337d5e9f0be1

This had already failed a month ago for the same reason in this workflow : https://argo.cildc6.org/archived-workflows/default/e7d48a9f-754b-42da-b8a3-e78d8211d3a9

log  : 

```
/opt/conda/lib/python3.9/site-packages/xesmf/backend.py:53: UserWarning: Latitude is outside of [-90, 90]
  warnings.warn('Latitude is outside of [-90, 90]')
/opt/conda/lib/python3.9/site-packages/xesmf/frontend.py:496: FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
  ds_out = xr.apply_ufunc(
Traceback (most recent call last):
  File "/argo/staging/script", line 68, in <module>
    ds_out.to_zarr(out_zarr, region={"time": target_idx_slice}, mode="a")
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2031, in to_zarr
    return to_zarr(
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1361, in to_zarr
    _validate_region(dataset, region)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1274, in _validate_region
    raise ValueError(
ValueError: when setting `region` explicitly in to_zarr(), all variables in the dataset to write must have at least one dimension in common with the region's dimensions ['time'], but that is not the case for some variables here. To drop these variables from this dataset before exporting to zarr, write: .drop(['bnds'])
```

**Comment by emileten** [comment]
This is a duplicate. Closing.
