### ISSUE TITLE
KACE-1-0-G tasmax cleaned ssp3 has nans

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#557]
Workflow : https://argo.cildc6.org/archived-workflows/default/cfefec08-0dc7-4913-b647-cc6571cb554a

Log : 

```
Validating gs://clean-b1dbca25/cmip6/ScenarioMIP/NIMS-KMA/KACE-1-0-G/ssp370/r1i1p1f1/day/tasmax/gr/v20200317.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 29, in clear_memory_intensive_tests
    _test_for_nans(d, v)
  File "/opt/dodola/dodola/core.py", line 684, in _test_for_nans
    assert ds[var].isnull().sum() == 0, "there are nans!"
AssertionError: there are nans!
```

**Comment by emileten** [comment]
I am looking at this. `standardize-cmip6` created nans ... with the inputs : 

```
in-zarr
gs://scratch-170cd6ec/cfefec08-0dc7-4913-b647-cc6571cb554a/e2e-kace-1-0-g-tasmax-vp8pn-1121105884/timesliced.zarr
out-zarr
gs://scratch-170cd6ec/cfefec08-0dc7-4913-b647-cc6571cb554a/e2e-kace-1-0-g-tasmax-vp8pn-1104684624/standardized.zarr
```

**Comment by emileten** [comment]
Ah, that's interesting. The nans are indeed in the output of the step. I retried that step with identical input, and the nans are _not_ in the new output. 

@brews sounds like something with the same flavor as #581 ?

**Comment by brews** [comment]
@emileten Hmm, yeah. Can you get the entire workflow to succeed by retrying it rather than resubmitting it?

**Comment by emileten** [comment]
@brews I tried doing that once and I am afraid I don't have the credentials : 

```
FATA[2022-02-18T08:39:24.373Z] rpc error: code = Unknown desc = pods "e2e-kace-1-0-g-tasmax-vp8pn-3186866825" is forbidden: User "system:serviceaccount:default:emile" cannot delete resource "pods" in API group "" in the namespace "default"
```

**Comment by brews** [comment]
@emileten Oh no! I triggered the retry.

**Comment by brews** [comment]
@emileten Yes! That's the difference between "retry" and "resubmit".

You might but it could be tricky because our workflows are so weirdly dense with heavy inputs. This KACE run isn't too far along so it's not too bad to just resubmit it.

**Comment by emileten** [comment]
Cool. Resubmitting it then 👍

**Comment by emileten** [comment]
Closing this, since this specific problem does not reappear.
