### ISSUE TITLE
HadGEM3-GC31-LL tasmax ssp585 min value out of range

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#558]
Workflow : https://argo.cildc6.org/archived-workflows/default/e46de2d6-5612-4dbf-92a6-c06060dc3b42

Log : 
```
Validating gs://clean-b1dbca25/cmip6/ScenarioMIP/MOHC/HadGEM3-GC31-LL/ssp585/r1i1p1f3/day/tasmax/gn/v20200114.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 32, in clear_memory_intensive_tests
    _test_temp_range(d, v)
  File "/opt/dodola/dodola/core.py", line 760, in _test_temp_range
    assert (ds[var].min() > 130) and (
AssertionError: tasmax values are invalid

```

**Comment by emileten** [comment]
Note that there is this note about this model in our recap dropbox table : 

```
tasmax data may have issues (status marked as "wontfix", severity "high")
```

So we shouldn't be surprised if values go off the rails.

**Comment by brews** [comment]
The tasmax range for this HadGEM3-GC31-11 data failing the validation range check is 181.58 K, 360.51 K.
