### ISSUE TITLE
UKESM1-0-LL tasmax all cleaned ssp values out of range

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#559]
Workflow : https://argo.cildc6.org/archived-workflows/default/269fc29e-fe52-4039-a33e-6774bd720415

Log example :  
```
Validating gs://clean-b1dbca25/cmip6/ScenarioMIP/MOHC/UKESM1-0-LL/ssp585/r1i1p1f2/day/tasmax/gn/v20190726.zarr
Traceback (most recent call last):
  File "/argo/staging/script", line 47, in <module>
    tasks = dask.compute(*tasks)
  File "/opt/conda/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 507, in get_async
    raise_exception(exc, tb)
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 315, in reraise
    raise exc
  File "/opt/conda/lib/python3.9/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)
  File "/opt/conda/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/argo/staging/script", line 32, in clear_memory_intensive_tests
    _test_temp_range(d, v)
  File "/opt/dodola/dodola/core.py", line 760, in _test_temp_range
    assert (ds[var].min() > 130) and (
AssertionError: tasmax values are invalid
```

**Comment by brews** [comment]
Looking at cleaning output tasmax ranges for UKESM1-0-LL:

- SSP585: 180.94 K, 371.42 K
- SSP126: 180.94 K, **376.38** K
- Historical: 179.92 K, 363.69 K
