### ISSUE TITLE
KACE-1-0-G fails at downscaling step due to excess GCS requests

### ISSUE THREAD

**Issue by emileten** [ClimateImpactLab/downscaleCMIP6#583]
We're been having this kind of problem several times in the recent days. 

Workflow : https://argo.cildc6.org/workflows/default/e2e-kace-1-0-g-tasmax-vnrff?tab=workflow&nodeId=e2e-kace-1-0-g-tasmax-vnrff-896964065&nodePanelView=inputs-outputs

Log : 

```
INFO:dodola.services:Starting dodola service apply_qplad with args=(), kwargs={'simulation': 'gs://scratch-170cd6ec/20673e25-3243-4ce1-b9bc-a1c3a6fecfec/e2e-kace-1-0-g-tasmax-vnrff-1337720762/regridded.zarr', 'qplad': 'gs://scratch-170cd6ec/20673e25-3243-4ce1-b9bc-a1c3a6fecfec/e2e-kace-1-0-g-tasmax-vnrff-3978685304/qplad-model.zarr', 'variable': 'tasmax', 'out': 'gs://downscaled-288ec5ac/stage/CMIP/NIMS-KMA/KACE-1-0-G/historical/r1i1p1f1/day/tasmax/gr/v20220218000404.zarr', 'sel_slice': None, 'isel_slice': {'lat': slice(276, 278, None)}, 'out_zarr_region': {'lat': slice(276, 278, None)}, 'root_attrs_json_file': '/tmp/global_attrs.json', 'new_attrs': None, 'wet_day_post_correction': False})
INFO:dodola.repository:Read gs://scratch-170cd6ec/20673e25-3243-4ce1-b9bc-a1c3a6fecfec/e2e-kace-1-0-g-tasmax-vnrff-1337720762/regridded.zarr
INFO:dodola.repository:Read gs://scratch-170cd6ec/20673e25-3243-4ce1-b9bc-a1c3a6fecfec/e2e-kace-1-0-g-tasmax-vnrff-3978685304/qplad-model.zarr
INFO:dodola.services:Using root attrs from /tmp/global_attrs.json
INFO:dodola.repository:Read attrs from /tmp/global_attrs.json
INFO:dodola.services:Slicing by isel_slice={'lat': slice(276, 278, None)}
INFO:dodola.services:Converting tasmax units to xclim pint compatible units
INFO:dodola.repository:Writing to Zarr Store region, region={'lat': slice(276, 278, None)}
INFO:dodola.repository:Dropping variables before Zarr region write: variables_to_drop=['lon', 'time']
ERROR:gcsfs:_request out of retries on exception: We encountered an internal error. Please try again., 503
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/retry.py", line 110, in retry_request
    return await func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/core.py", line 322, in _request
    validate_response(status, contents, path)
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/retry.py", line 97, in validate_response
    raise HttpError(error)
gcsfs.retry.HttpError: We encountered an internal error. Please try again., 503
Traceback (most recent call last):
  File "/opt/conda/bin/dodola", line 33, in <module>
    sys.exit(load_entry_point('dodola', 'console_scripts', 'dodola')())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/dodola/dodola/cli.py", line 393, in apply_qplad
    services.apply_qplad(
  File "/opt/dodola/dodola/services.py", line 34, in service_logger
    func(*args, **kwargs)
  File "/opt/dodola/dodola/services.py", line 504, in apply_qplad
    storage.write(out, adjusted_ds, region=out_zarr_region)
  File "/opt/dodola/dodola/repository.py", line 69, in write
    x.to_zarr(url_or_path, region=region, mode="a", compute=True)
  File "/opt/conda/lib/python3.9/site-packages/xarray/core/dataset.py", line 2031, in to_zarr
    return to_zarr(
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1414, in to_zarr
    dump_to_store(dataset, zstore, writer, encoding=encoding)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/api.py", line 1124, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/zarr.py", line 552, in store
    self.set_attributes(attributes)
  File "/opt/conda/lib/python3.9/site-packages/xarray/backends/zarr.py", line 477, in set_attributes
    self.zarr_group.attrs.put(attributes)
  File "/opt/conda/lib/python3.9/site-packages/zarr/attrs.py", line 109, in put
    self._write_op(self._put_nosync, d)
  File "/opt/conda/lib/python3.9/site-packages/zarr/attrs.py", line 73, in _write_op
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/zarr/attrs.py", line 112, in _put_nosync
    self.store[self.key] = json_dumps(d)
  File "/opt/conda/lib/python3.9/site-packages/zarr/storage.py", line 1111, in __setitem__
    self.map[key] = value
  File "/opt/conda/lib/python3.9/site-packages/fsspec/mapping.py", line 152, in __setitem__
    self.fs.pipe_file(key, maybe_convert(value))
  File "/opt/conda/lib/python3.9/site-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/opt/conda/lib/python3.9/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/core.py", line 853, in _pipe_file
    return await simple_upload(
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/core.py", line 1357, in simple_upload
    j = await fs._call(
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/core.py", line 330, in _call
    status, headers, info, contents = await self._request(
  File "/opt/conda/lib/python3.9/site-packages/decorator.py", line 221, in fun
    return await caller(func, *(extras + args), **kw)
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/retry.py", line 130, in retry_request
    raise e
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/retry.py", line 110, in retry_request
    return await func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/core.py", line 322, in _request
    validate_response(status, contents, path)
  File "/opt/conda/lib/python3.9/site-packages/gcsfs/retry.py", line 97, in validate_response
    raise HttpError(error)
gcsfs.retry.HttpError: We encountered an internal error. Please try again., 503
```

It's pretty far along so I'd like to retry this instead of re-running the whole thing, but I don't have the credentials for this, @brews. Would you mind doing it ?

**Comment by emileten** [comment]
Thanks a lot @brews. The workflow is done ! 

Yes, let's note that somewhere and do it when we have time (the k8s permissions). 

I will have a look at this recurring bug as well my monday.

**Comment by brews** [comment]
I think it's okay to close this. I'm working on updating the packages over on this draft PR https://github.com/ClimateImpactLab/dodola/pull/183.
